In [1]:
import numpy as np

arr = np.arange(6)
print(arr)
print(arr.dtype)


[0 1 2 3 4 5]
int64


In [2]:
arr1 = np.array([1.5, 2.6, 3.7])
is_float64 = arr1.dtype == np.float64
print(is_float64)


True


In [3]:
arr2 = np.array([1+2j, 3-4j, 5+6j], dtype=np.complex128)
print(arr2)
print(arr2.dtype)

[1.+2.j 3.-4.j 5.+6.j]
complex128


In [4]:
arr4=np.array([1,5,7,8])
arr5 = arr4.astype(np.float32)
print(arr5)
print(arr5.dtype)

[1. 5. 7. 8.]
float32


In [5]:
arr_float64 = np.array([0.123456789, 1.23456789, 12.3456789], dtype=np.float64)

arr_float32 = arr_float64.astype(np.float32)

print("Original array with float64 data type:")
print(arr_float64)

print("\nArray after converting to float32:")
print(arr_float32)


Original array with float64 data type:
[ 0.12345679  1.23456789 12.3456789 ]

Array after converting to float32:
[ 0.12345679  1.2345679  12.345679  ]


In [6]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr7 = np.arange(10).reshape(2, 5)
print(array_attributes(arr7))


((2, 5), 10, dtype('int64'))


In [7]:
def array_dimension(arr):
    return arr.ndim

arr8 = np.arange(10).reshape(2, 5)
print(array_dimension(arr8))


2


In [8]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr9 = np.arange(10).reshape(2, 5)
print(item_size_info(arr9))


(8, 80)


In [9]:
def array_strides(arr):
    return arr.strides

arr10 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print("Array:")
print(arr10)
print("\nStrides of the array:")
print(array_strides(arr10))


Array:
[[1 2 3]
 [4 5 6]]

Strides of the array:
(12, 4)


Strides are a tuple of integers indicating the number of bytes to step in each dimension when traversing the array. The length of the strides tuple is equal to the number of dimensions in the array.

For example, consider a 2D array arr with shape (3, 4) and dtype np.int32. If the strides are (16, 4), it means that to move from one row to the next, you need to move 16 bytes (4 elements of int32, each occupying 4 bytes), and to move from one column to the next, you need to move 4 bytes (1 element of int32).

In [10]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr11 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:")
print(arr11)
print("Shape and Strides:", shape_stride_relationship(arr11))


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape and Strides: ((3, 3), (24, 8))


In [11]:
def create_zeros_array(n):
    return np.zeros(n)

n = 5
print("Zeros Array:", create_zeros_array(n))


Zeros Array: [0. 0. 0. 0. 0.]


In [12]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

rows, cols = 3, 4
print("Ones Matrix:")
print(create_ones_matrix(rows, cols))


Ones Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start, stop, step = 1, 10, 2
print("Range Array:", generate_range_array(start, stop, step))


Range Array: [1 3 5 7 9]


In [14]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start, stop, num = 1.5, 9.5, 5
print("Linear Space Array:", generate_linear_space(start, stop, num))


Linear Space Array: [1.5 3.5 5.5 7.5 9.5]


In [15]:
def create_identity_matrix(n):
    return np.eye(n)
n = 3
print("Identity Matrix:")
print(create_identity_matrix(n))


Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
def list_to_numpy_array(py_list):
    return np.array(py_list)
python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)


[1 2 3 4 5]


In [17]:
original_array = np.array([1, 2, 3, 4, 5])
view_array = original_array.view()
view_array[0] = 10
print("Original Array:", original_array)
print("View Array:", view_array)

Original Array: [10  2  3  4  5]
View Array: [10  2  3  4  5]


 numpy.view creates a new array object (view_array) that shares the same data as the original array (original_array). Modifying the view array also affects the original array because they share the same data.

In [18]:
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_array = concatenate_arrays(arr1, arr2)
print("Concatenated Array:", concatenated_array)


Concatenated Array: [1 2 3 4 5 6]


In [19]:
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])
stacked_array = stack_arrays_vertically([array1, array2, array3])
print(stacked_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
def create_integer_array(start, stop, step):
    return np.arange(start, stop+1, step, dtype=int)

integer_array = create_integer_array(1, 10, 2)
print(integer_array)

[1 3 5 7 9]


In [21]:
def equally_spaced_values():
    return np.linspace(0, 1, 10)

spaced_array = equally_spaced_values()
print(spaced_array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [22]:
def logarithmically_spaced_values():
    return np.logspace(0, 3, 5)

log_spaced_array = logarithmically_spaced_values()
print(log_spaced_array)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [23]:
import pandas as pd
np.random.seed(0)
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)


    A   B   C
0  45  48  65
1  68  68  10
2  84  22  37
3  88  71  89
4  89  13  59


In [24]:
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(dataframe, column):
    dataframe[column] = np.where(dataframe[column] < 0, 0, dataframe[column])

data = {'A': [1, -2, 3, -4],
        'B': [5, 6, -7, 8],
        'C': [-9, 10, 11, -12]}
df1 = pd.DataFrame(data)
print("DataFrame before replacement:")
print(df1)

replace_negatives_with_zeros(df1, 'B')
print("\nDataFrame after replacing negatives with zeros in column 'B':")
print(df1)


DataFrame before replacement:
   A  B   C
0  1  5  -9
1 -2  6  10
2  3 -7  11
3 -4  8 -12

DataFrame after replacing negatives with zeros in column 'B':
   A  B   C
0  1  5  -9
1 -2  6  10
2  3  0  11
3 -4  8 -12


In [25]:
arr12 = np.array([10, 20, 30, 40, 50])
print(arr12[2])



30


In [26]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])

6


In [27]:
arr13 = np.array([3, 8, 2, 10, 5, 7])
greater_than_5 = arr13[arr13 > 5]
print(greater_than_5)


[ 8 10  7]


In [28]:
arr14 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr14[2:6]
print(sliced_array)

[3 4 5 6]


In [29]:
arr15 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr15[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [30]:
def extract_elements_2d(arr, indices):
    return arr[np.arange(arr.shape[0])[:, None], indices]

arr16 = np.array([[1, 2, 3], [4, 5, 6]])
indices = np.array([[0, 2], [1, 0]])
print(extract_elements_2d(arr16, indices))


[[1 3]
 [5 4]]


In [31]:
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr17 = np.array([1, 2, 3, 4, 5, 6])
threshold = 3
result = filter_greater_than(arr, threshold)
print(result) 

[4 5]


In [32]:
def extract_elements_3d(array_3d, indices_dim1, indices_dim2, indices_dim3):
    
    return array_3d[indices_dim1, indices_dim2, indices_dim3]


array_3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

indices_dim1 = np.array([0, 1, 2])
indices_dim2 = np.array([1, 0, 2])
indices_dim3 = np.array([2, 1, 0])

result1 = extract_elements_3d(array_3d, indices_dim1, indices_dim2, indices_dim3)
print(array_3d,"\n")
print(result1)  


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 

[ 6 11 25]


In [33]:
def satisfy_both_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]   #Compute the truth value of x1 AND x2 element-wise.

arr19 = np.array([1, 2, 3, 4, 5, 6])
condition1 = arr19 > 2
condition2 = arr19 % 2 == 0
result2 = satisfy_both_conditions(arr19, condition1, condition2)
print(result2) 

[4 6]


In [34]:
def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr20 = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = np.array([0, 1])
col_indices = np.array([1, 2])
result3 = extract_elements_2d(arr20, row_indices, col_indices)
print(arr20,"\n")
print(result3)  

[[1 2 3]
 [4 5 6]] 

[2 6]


In [35]:
arr21 = np.random.randint(0, 10, size=(3, 3))
result4 = arr + 5
print(result4)

[ 5  6  7  8  9 10]


In [36]:
arr22 = np.array([[2, 3, 4]])
arr23 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

result5 = arr22.T * arr23

print(result5)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [37]:
arr24 = np.array([[2, 3, 4, 5]])
arr25 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

result6 = arr24.T + arr25

print(result6)

[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]
 [15 16 17]]


In [38]:
arr26 = np.array([[1, 2, 3], [4, 5, 6]])  
arr27 = np.array([[2, 3], [4, 5]])        
arr27_reshaped = arr27[:,:, np.newaxis] 
result7 = arr26 * arr27_reshaped

print("Result:")
print(result7)

Result:
[[[ 2  4  6]
  [12 15 18]]

 [[ 4  8 12]
  [20 25 30]]]


arr27[: , : , np.newaxis] reshapes arr27 to have an additional axis at the end, effectively changing its shape from (2, 2) to (2, 2, 1). This reshaping is done using NumPy's slicing notation. The np.newaxis is used to add a new axis.

In [39]:
arr28 = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr28,axis=0)

array([2.5, 3.5, 4.5])

In [40]:
arr29 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr29)
np.max(arr29,axis=1)

[[1 2 3]
 [4 5 6]]


array([3, 6])

In [41]:
arr30 = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr30, axis=0)

print(arr30)
print("Index of maximum value in each column:")
for col, idx in enumerate(max_indices):
    print(f"Column {col}: Index {idx}")

[[1 2 3]
 [4 5 6]]
Index of maximum value in each column:
Column 0: Index 1
Column 1: Index 1
Column 2: Index 1


In [42]:
def moving_sum_along_rows(arr, window_size):
    
    padded_arr = np.pad(arr, ((0, 0), (window_size - 1, 0)), mode='constant')
    
    cumsum = np.cumsum(padded_arr, axis=1)
    
    moving_sum = cumsum[:, window_size:] - cumsum[:, :-window_size]
    return moving_sum

arr31 = np.array([[1, 2, 3], [4, 5, 6]])
window_size = 2
moving_sum = moving_sum_along_rows(arr31, window_size)
print(moving_sum)

[[ 3  5]
 [ 9 11]]


In [43]:
arr32 = np.array([[2, 4, 6], [4, 5, 7]])
all_even_columns = np.all(arr32 % 2 == 0, axis=0)

print(all_even_columns)

[ True False False]


In [44]:
def reshape_array(arr, m, n):
    reshaped_matrix = arr.reshape(m, n)
    return reshaped_matrix

original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2  
n = 3  

reshaped_matrix = reshape_array(original_array, m, n)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [45]:
def flatten_matrix(input_matrix):
    flattened_array = input_matrix.flatten()
    return flattened_array

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [46]:
def concatenate_arrays(array1, array2, axis=0):
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(concatenated_array_axis0)

concatenated_array_axis1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:")
print(concatenated_array_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [47]:
def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):

    for idx, val in zip(indices_to_insert, values_to_insert):
        original_array = np.insert(original_array, idx, val)

    
    original_array = np.delete(original_array, indices_to_delete)

    return original_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


[ 1 10 11  4  5]


In [48]:
arr33 = np.random.randint(1, 100, size=(5,1))
arr34 = np.arange(1, 11)

result8 = arr33 + arr34
print(arr33)
print(arr34,"\n")
print("Element wise sum \n")
print(result8)


[[10]
 [21]
 [81]
 [70]
 [80]]
[ 1  2  3  4  5  6  7  8  9 10] 

Element wise sum 

[[11 12 13 14 15 16 17 18 19 20]
 [22 23 24 25 26 27 28 29 30 31]
 [82 83 84 85 86 87 88 89 90 91]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]]


In [49]:
arr35 = np.arange(10, 0, -1)
arr36 = np.arange(1, 11)

result9 = arr35 - arr36
print(result9)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [50]:
arr37 = np.random.randint(1, 100, size=(5,))
arr38 = np.arange(1, 6)

result10 = arr35 * arr36
print(result10)


[10 18 24 28 30 30 28 24 18 10]


In [51]:
arr39 = np.arange(2, 11, 2)
arr40 = np.arange(1, 6)

result11 = arr39 / arr40
print(result11)


[2. 2. 2. 2. 2.]


In [52]:
arr41 = np.arange(1, 6)
arr42 = np.flip(arr41)

result12 = np.power(arr41, arr42)
print(arr41,"\n")
print(arr42,"\n")
print(result12)


[1 2 3 4 5] 

[5 4 3 2 1] 

[ 1 16 27 16  5]


In [53]:
def count_substring_occurrences(arr, substring):
    
    occurrences = [string.count(substring) for string in arr]
    
    
    total_occurrences = sum(occurrences)
    
    return total_occurrences

arr43 = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

occurrences = count_substring_occurrences(arr43, substring)
print("Total occurrences of '{}' in the array: {}".format(substring, occurrences))


Total occurrences of 'hello' in the array: 3


In [54]:
def extract_uppercase_chars(arr44):
    
    def extract_uppercase(string):
        return ''.join(char for char in string if char.isupper())

    
    extract_uppercase_func = np.frompyfunc(extract_uppercase, 1, 1)
    uppercase_array = extract_uppercase_func(arr44)

    return uppercase_array

arr44 = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase_chars(arr44)
print("Uppercase characters:", uppercase_chars)


Uppercase characters: ['H' 'W' 'OAI' 'GPT']


In [55]:
def replace_substring(arr45, old_substring, new_substring):
    
    def replace_func(string):
        return string.replace(old_substring, new_substring)

    
    replace_func = np.frompyfunc(replace_func, 1, 1)
    replaced_array = replace_func(arr45)

    return replaced_array


arr45 = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr45, 'apple', 'orange')
print("Original array:", arr45)
print("Array with replaced substrings:", new_arr)


Original array: ['apple' 'banana' 'grape' 'pineapple']
Array with replaced substrings: ['orange' 'banana' 'grape' 'pineorange']


In [56]:
def concatenate_strings(arr46, arr47):
    
    concatenated_array = np.char.add(arr46, arr47)
    
    return concatenated_array

arr46 = np.array(['Hello', 'World'])
arr47 = np.array(['Open', 'AI'])

result13 = concatenate_strings(arr46, arr47)
print("Concatenated array:", result13)


Concatenated array: ['HelloOpen' 'WorldAI']


In [57]:
def longest_string_length(arr47):
    
    vectorized_len = np.vectorize(len)

    
    lengths = vectorized_len(arr47)

    
    max_length = np.max(lengths)

    return max_length

arr47 = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string_length(arr47)
print("Length of the longest string:", longest_length)


Length of the longest string: 9


In [58]:
dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Mean: 529.37
Median: 553.0
Variance: 88216.6731
Standard Deviation: 297.0129173958601


In [59]:
data = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)


25th percentile: 21.25
75th percentile: 65.25


In [60]:
array48 = np.array([1, 2, 3, 4, 5])
array49 = np.array([5, 4, 3, 2, 1])

correlation_coefficient = np.corrcoef(array48, array49)[0, 1]

print("Correlation Coefficient:", correlation_coefficient)


Correlation Coefficient: -0.9999999999999999


In [61]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[19 22]
 [43 50]]


In [62]:
data1 = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(data1, 10)
percentile_50 = np.percentile(data1, 50)
percentile_90 = np.percentile(data1, 90)
quartile_1 = np.percentile(data1, 25)
quartile_3 = np.percentile(data1, 75)

print("10th percentile:", percentile_10)
print("50th percentile (median):", percentile_50)
print("90th percentile:", percentile_90)
print("First quartile (25th percentile):", quartile_1)
print("Third quartile (75th percentile):", quartile_3)


10th percentile: 147.20000000000002
50th percentile (median): 536.5
90th percentile: 899.0
First quartile (25th percentile): 299.25
Third quartile (75th percentile): 846.5


In [63]:
arr50 = np.array([10, 20, 30, 40, 50])

index = np.where(arr50 == 30)[0]

print("Index of element 30:", index)


Index of element 30: [2]


In [64]:
arr51 = np.random.randint(1, 100, size=10)

sorted_arr1 = np.sort(arr51)

print("Original array:", arr51)
print("Sorted array:", sorted_arr1)


Original array: [25 80 42 19 41 55 80 12 39 94]
Sorted array: [12 19 25 39 41 42 55 80 80 94]


In [65]:
arr52 = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr52[arr52 > 20]

print("Filtered elements:", filtered_arr)


Filtered elements: [25 42 30]


In [66]:
arr53 = np.array([12, 25, 6, 42, 8, 30])

filtered_arr1 = arr[arr53 % 3 == 0]

print("Filtered elements:", filtered_arr1)


Filtered elements: [0 2 3 5]


In [67]:
arr54 = np.array([12, 25, 6, 42, 8, 30])

filtered_arr2 = arr54[(arr54 >= 20) & (arr54 <= 40)]

print("Filtered elements:", filtered_arr2)


Filtered elements: [25 30]


In [68]:
arr55 = np.array([1, 2, 3])

byte_order = arr55.dtype.byteorder

print("Byte order of the given array is ", byte_order)


Byte order of the given array is  =


In [69]:
arr56 = np.array([1, 2, 3], dtype=np.int32)
arr56.byteswap(True)
print("Byte-swapped array:", arr56)


Byte-swapped array: [16777216 33554432 50331648]


In [70]:
arr57 = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr57.newbyteorder()
print("Swapped byte order array:", swapped_arr)


Swapped byte order array: [16777216 33554432 50331648]


In [71]:
arr58 = np.array([1, 2, 3], dtype=np.int32)
swapped_arr4 = arr.newbyteorder('S')
print("Swapped byte order array:", swapped_arr4)


Swapped byte order array: [                 0  72057594037927936 144115188075855872
 216172782113783808 288230376151711744 360287970189639680]


In [72]:
arr59 = np.array([1, 2, 3], dtype=np.int32)
byte_order4 = arr.dtype.byteorder
print("Byte order:", byte_order4)


Byte order: =


In [73]:
arr60 = np.arange(1, 11)
copy_arr5 = arr1.copy()
copy_arr5[0] = 100
print("Original array arr1:", arr60)
print("Modified copy array copy_arr:", copy_arr5)


Original array arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array copy_arr: [100   2   3]


In [74]:
matrix4 = np.random.randint(1, 100, size=(3, 3))
view_slice = matrix4[:2, :2]
view_slice[0, 0] = 999
print("Original matrix:\n", matrix4)
print("Modified view_slice:\n", view_slice)


Original matrix:
 [[999  96  45]
 [ 89  25  68]
 [ 83   4  77]]
Modified view_slice:
 [[999  96]
 [ 89  25]]


In [75]:
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print("Original array_a:\n", array_a)
print("Modified view_b:\n", view_b)


Original array_a:
 [[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
Modified view_b:
 [[ 6  7]
 [ 9 10]]


In [76]:
orig_array5 = np.arange(1, 9).reshape(2, 4)
reshaped_view4 = orig_array5.reshape(4, 2)
reshaped_view4[0, 0] = 99
print("Original orig_array:\n", orig_array5)
print("Modified reshaped_view:\n", reshaped_view4)


Original orig_array:
 [[99  2  3  4]
 [ 5  6  7  8]]
Modified reshaped_view:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [78]:
data7 = np.random.randint(1, 10, size=(3, 4))

data_copy10 = data7[data7 > 5].copy()

data_copy10[0] = 99
print("Original data:\n", data7)
print("Modified data_copy:\n", data_copy10)


Original data:
 [[4 8 6 4]
 [5 6 4 4]
 [8 8 4 3]]
Modified data_copy:
 [99  6  6  8  8]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

addition_result = A + B
subtraction_result = A - B

print("Addition result:\n", addition_result)
print("Subtraction result:\n", subtraction_result)


In [ ]:
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

multiplication_result = np.dot(C, D)

print("Multiplication result:\n", multiplication_result)


In [ ]:
E = np.array([[1, 2, 3], [4, 5, 6]])
transpose_E = E.T

print("Original matrix E:\n", E)
print("Transposed matrix E:\n", transpose_E)


In [ ]:
E = np.array([[1, 2, 3], [4, 5, 6]])
transpose_E = E.T

print("Original matrix E:\n", E)
print("Transposed matrix E:\n", transpose_E)


In [ ]:
G = np.array([[1, 2], [3, 4]])
inverse_G = np.linalg.inv(G)

print("Matrix G:\n", G)
print("Inverse of G:\n", inverse_G)
